Resources:
  LBCAccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
      TableName: "LBC_Accounts"
      BillingMode: PAY_PER_REQUEST
