Resources:
  LBCTermsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "termId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "termId"
          KeyType: "HASH"
      TableName: "LBC_Terms"
      BillingMode: PAY_PER_REQUEST