Resources:
  LBCTestTemplatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "templateId"
          AttributeType: "S"
        - AttributeName: "title"
          AttributeType: "S"
        - AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "templateId"
          KeyType: "HASH"
      TableName: "LBC_TestTemplates"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "UsernameTitleIndex"
          KeySchema:
            - AttributeName: "username"
              KeyType: "HASH"
            - AttributeName: "title"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "KEYS_ONLY"
        - IndexName: "CostIndex"
          KeySchema:
            - AttributeName: "clothingType"
              KeyType: "HASH"
            - AttributeName: "cost"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "KEYS_ONLY"